.TH lxqt-config-cursor "1" "September 2012" "LXQt\ 0.7.0" "LXQt\ Cursor settings"
.SH NAME
lxqt-config-cursor \- Application of \fBLXQt\fR: the faster and lighter Qt Desktop Environment
.SH SYNOPSIS
.B lxqt-config-cursor
.br
.SH DESCRIPTION
This is a simple GUI cursor theme configuration (at the moment) for the LXQt desktop environment.
Also can manage theme installation for it (locally for/per user only).
.P
\fBLXQt\fR is an advanced, easy-to-use, and fast desktop environment based on Qt
technologies, ships several core desktop components, all of which are optional:
.P
 * Panel
 * Desktop
 * Application launcher
 * Settings center \fI(related to this)\fR
 * Session handler
 * Polkit handler
 * SSH password access
 * Display manager handler
.P
These components perform similar actions to those available in other desktop
environments, and their name is self-descriptive.  They are usually not launched
by hand but automatically, when choosing a \fBLXQt\-qt\fR session in the Display
Manager.
.P
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxqt/lxqt/issues
.SH "SEE ALSO"
\fBLXQt\fR has been tailored for users who value simplicity, speed, and
an intuitive interface, also intended for less powerful machines. See also:
.\" any module must refers to session app, for more info on start it
.P
\fBlxqt-config(1)\fR  LXQt application for performing settings on many applications
.P
.SH AUTHOR
This manual page was created by \fBPICCORO Lenz McKAY\fR \fI<mckaygerhard@gmail.com>\fR
for \fBLXQt\fR project and VENENUX GNU/Linux but can be used by others.
