.TH lxqt-config "1" "September 2012" "LXQt 0.7.0" "LXQt System Settings"
.SH NAME
lxqt-config \- \fBLXQt\fR Settings Center for all related modules and
applications
.SH SYNOPSIS
.B lxqt-config
.br
.SH DESCRIPTION
This application is a settings center for all environment related applications
and all config software installed and registered by the \fBLXQt\fR desktop
environment.
.P
\fBLXQt\fR is an advanced, easy-to-use, and fast desktop environment based on Qt
technologies and ships several core desktop components, all of which are
optional:
.P
 * Panel
 * Desktop
 * Application launcher
 * Settings center \fI(this)\fR
 * Session handler
 * Polkit handler
 * SSH password access
 * Display manager handler
.P
These components perform actions like their counterparts in other desktop
environments and their names are self-descriptive. They are usually not
launched manually but automatically, when an \fBLXQt\fR session is chosen in the
Display Manager.
.P
.SH LXQt Settings Center related applications
.P
\fBLXQt\fR has various config applications:
.P
 * Mouse settings: (\fBlxqt-config-mouse\fR)
 * Desktop settings: (\fBlxqt-config-desktop\fR)
 * Appereance settings: (\fBlxqt-config-appearance\fR)
 * Session settings: (\fBlxqt-config-session\fR)
 * Notification settings: (\fBlxqt-config-notificationd\fR)
.P
All of this can also be found in Settings or Preferences menu; please consult
the respective manpages.
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxqt/lxqt/issues
.SH "SEE ALSO"
\fBLXQt\fR has been tailored for users who value simplicity, speed, and an
intuitive interface. LXQt is also intended for less powerful machines. See:

.\" any module must refer to session app, for more info on starting it
.P
 * Mouse settings: \fBlxqt-config-mouse(1)\fR
.P
 * Desktop settings: \fBlxqt-config-desktop(1)\fR
.P
 * Appeareance settings: \fBlxqt-config-appearance(1)\fR
.P
 * Session settings: \fBlxqt-config-session(1)\fR
.P
 * Notification settings: \fBlxqt-config-notificationd(1)\fR
.P
.SH AUTHOR
This manual page was created by \fBPICCORO Lenz McKAY\fR \fI<mckaygerhard@gmail.com>\fR
for \fBLXQt\fR project and VENENUX GNU/Linux but can be used by others.
