#!/bin/sh

#=============================================================================
# Copyright 2018 Alf Gaida <agaida@siduction.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#=============================================================================

# lxqt-transupdate
# Update LXQt translation files.

# just to be sure - for distributions that user qtchooser
# Debian and derivatives, Fedora, FreeBSD, Mageia, OpenMandriva, PCLinuxOS
export QT_SELECT=5

TEMPLATES=$(find . -name \*.ts | grep -v '_')
for i in $TEMPLATES; do
  echo "\n\n==== $i ====\n"
  TRANSDIR=$(dirname $i)
  SOURCEDIR=$(dirname $TRANSDIR)
  # template-update
  echo "== Template Update =="
  echo "lupdate $SOURCEDIR -ts $i -locations absolute -no-obsolete\n"
  lupdate  $SOURCEDIR -ts $i -locations absolute -no-obsolete
  echo
  echo "== Language updates =="
  echo "lupdate $SOURCEDIR -ts $TRANSDIR/*.ts -locations absolute -no-obsolete\n"
  lupdate  $SOURCEDIR -ts $TRANSDIR/*_*.ts -locations absolute -no-obsolete
done
